CREATE TABLE users
(
    pk               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id               UUID                                     NOT NULL,
    username         VARCHAR(255),
    first_name       VARCHAR(255)                             NOT NULL,
    middle_name      VARCHAR(255),
    last_name        VARCHAR(255)                             NOT NULL,
    email            VARCHAR(255),
    password         VARCHAR(255),
    roles            VARCHAR(255),
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by VARCHAR(255),
    is_active        BOOLEAN DEFAULT FALSE                    NOT NULL,
    is_deleted       BOOLEAN DEFAULT FALSE                    NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (pk)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_id UNIQUE (id);