CREATE TABLE note
(
    pk               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id               UUID                                     NOT NULL,
    title            VARCHAR(255)                             NOT NULL,
    content          JSONB,
    tags             JSONB,
    user_id          INTEGER                                  NOT NULL,
    deleted          BOOLEAN                                  NOT NULL,
    deleted_at       TIMESTAMP WITHOUT TIME ZONE,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by VARCHAR(255),
    version          INTEGER                                  NOT NULL,
    CONSTRAINT pk_note PRIMARY KEY (pk)
);

ALTER TABLE note
    ADD CONSTRAINT uc_note_id UNIQUE (id);

ALTER TABLE note
    ADD CONSTRAINT FK_NOTE_ON_USER FOREIGN KEY (user_id) REFERENCES users (pk);